### ISSUE TITLE
OneLondon: All Home buttons should forward users to Landing page

### ISSUE THREAD

**Issue by kuvakina** [RippleOSI/OneLondon_OpenPlatform#10]
At the moment Home (icon) button and logo near it forward users to Landing page:
![bb2.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/93d20965-a61e-413b-8505-e85477e9bfd0)

But Home button in breadcrumb:
![bb1.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/6cf5ac2f-fbcd-4f5c-a85c-c39f98406410)
forward user to search on MPV page:
![bb3.png](https://images.zenhubusercontent.com/5cacbbef8d0ceb76ea94b3f3/edda38ca-7917-41e6-a0da-d325d34b6da4)

**Comment by kuvakina** [comment]
@PhilBarrett now Home button in breadcrumb forward user to Landing page

**Comment by PhilBarrett** [comment]
Reviewed and closing, thanks
