### ISSUE TITLE
Problem selecting an entry in patient summary

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/OneLondon_OpenPlatform#12]
the order of the items and the highlighting of the entry selected, doesn't work correctly.

**Comment by kuvakina** [comment]
@PhilBarrett these issues also relevant for Helm-RA and order issue related to server side and highlight related to client side, so I created separate issues for 

**Bogdan, client side** : https://app.zenhub.com/workspaces/ripple-combined-project-space-5c8be494fd0adb6f09c83d6b/issues/pulsetile/pulsetile-ra/91

**Dima, server side** : https://app.zenhub.com/workspaces/ripple-combined-project-space-5c8be494fd0adb6f09c83d6b/issues/pulsetile/pulsetile-ra/90

**Comment by tony-shannon** [comment]
Alexandra to close this , as others opened instead

**Comment by kuvakina** [comment]
I've updated related issues above. As we separated this issue in two, I'm closing this one.
