### ISSUE TITLE
Change One London login theme

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/OneLondon_OpenPlatform#4]
to change to One London theme 
Simon has the mockups

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 
This issue has been done

**Comment by PhilBarrett** [comment]
Thanks for the update @BogdanScherban,  I can't see the background image though, can you revisit please

**Comment by BogdanScherban** [comment]
@PhilBarrett 
Background is added:
![image](https://user-images.githubusercontent.com/39263134/56136167-e7cbb480-5f9a-11e9-9689-c3dcdcc66a27.png)

**Comment by PhilBarrett** [comment]
Completed
