### ISSUE TITLE
One London Bugs/refinement

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/OneLondon_OpenPlatform#5]
-  [x] Tunnel positioning too low (Simon)
-  [x] Responsive issues of background image and logo (Simon) - *parked for now*
-  [x] One London logo is stretched in top left (Simon)
-  [x]  Saving doesn't work on edit patient (Bogdan) - 15/20mins
-  [x] Demographics not returning in SPV Patient Banner (Dima)
-  [x] CHI number to change back to NHS Number (Bogdan)
-  [x] Remove Age from MPV view (Bogdan)
-  [x] Turn off search cog (Bogdan)
- [x] Remove rings from headers
- [x] clicking from MPV to spv it  returns different demographics (*parked*)

**Comment by BogdanScherban** [comment]
These issues were done:
> Tunnel positioning too low (Simon)
> CHI number to change back to NHS Number (Bogdan)
> Remove Age from MPV view (Bogdan)
> Turn off search cog (Bogdan)

**Comment by BogdanScherban** [comment]
This issue also has been done:
> Saving doesn't work on edit patient (Bogdan) - 15/20mins

**Comment by simongamester** [comment]
@BogdanScherban Re: One London logo is stretched in top left (Simon) - There appears to be a height attribute on the img tag for the logo. Suggest you remove this. The image is correctly sizes anyway, so needs no widths or sizes set.

**Comment by kuvakina** [comment]
@PhilBarrett Dima finished with his task.
Bogdan'll remove attributes for logo

**Comment by PhilBarrett** [comment]
Thanks @kuvakina I believe Bogdan and Simon have discussed the background image too, so an update here would be helpful when he finishes the logo attribute change please

**Comment by BogdanScherban** [comment]
@simongamester @tony-shannon 
Logo was fixed. Is it OK?
![image](https://user-images.githubusercontent.com/39263134/56135157-ca95e680-5f98-11e9-93c6-fe5b1a37dfab.png)

**Comment by PhilBarrett** [comment]
Yes, thanks Bogdan

**Comment by simongamester** [comment]
No quite, you just need to take out the height attribute as the native height of the image is not 38px.

![Screenshot 2019-04-15 at 14 11 55](https://user-images.githubusercontent.com/8059219/56135385-87337c00-5f88-11e9-8163-2024944f34b8.png)

**Comment by BogdanScherban** [comment]
@simongamester 
Done
![image](https://user-images.githubusercontent.com/39263134/56136071-adfaae00-5f9a-11e9-882f-52138e56324b.png)

**Comment by simongamester** [comment]
@BogdanScherban Looks good!

**Comment by BogdanScherban** [comment]
@PhilBarrett @tony-shannon 
This issue was done:
>  clicking from MPV to spv it returns different demographics (parked)

**Comment by kuvakina** [comment]
All the issues were fixed.

**Comment by tony-shannon** [comment]
can we recheck as the one london demo is down please

**Comment by tony-shannon** [comment]
@DmitrySolyannik  restarted containers and working well now
London instance snapshotted ; as Image on AWS
Tony
