### ISSUE TITLE
DDS test data from Chrisp Street practice

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/OneLondon_OpenPlatform#7]

**Comment by PhilBarrett** [comment]
Need to connect to DDS test patients from Chrisp Street practice now the API is ready

Please ask PB for username and password for DDS API access.

Instructions attached and test patients expected include:

9999999484
9999999492
9999999506
9999999468

[https://app.zenhub.com/files/178211254/5c21286d-313e-427a-af4e-88ca5255caf5/download](https://app.zenhub.com/files/178211254/5c21286d-313e-427a-af4e-88ca5255caf5/download)

[https://app.zenhub.com/files/178211254/4e2b3d96-329f-405c-be1e-4e454199440e/download](https://app.zenhub.com/files/178211254/4e2b3d96-329f-405c-be1e-4e454199440e/download)

**Comment by tony-shannon** [comment]
contact is josh.atkinson at endeavourhealth dot org

**Comment by PhilBarrett** [comment]
[https://app.zenhub.com/files/178211254/7f5639ac-6d08-4bc5-bac5-4eddc843e4ff/download](https://app.zenhub.com/files/178211254/7f5639ac-6d08-4bc5-bac5-4eddc843e4ff/download)

**Comment by tony-shannon** [comment]
its now clear that an N3 connection is needed to connect to Chrisp Street practice, so for now we will fall back on other DDS test patients and give Dr B a login to onelondon,.r.f

**Comment by DmitrySolyannik** [comment]
@tony-shannon , @PhilBarrett 
Waiting for DDS team changes, functionality for retrieving heading data, added in this PR
https://github.com/QEWD-Courier/QEWD-Courier/pull/74

**Comment by PhilBarrett** [comment]
Closing as dependent on HSCN connection
