### ISSUE TITLE
Demographics API error

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/OneLondon_OpenPlatform#8]
When I log in as a test user rob tweed, I receive the following error

![Screen Shot 2019-04-30 at 16.13.32.png](https://images.zenhubusercontent.com/5c90c9fcd76ef51f6b0fddfd/f2b36c45-52f8-4436-abcc-9f1fec2b3ff5)

{error: "patientId null is invalid", path: "/api/demographics/:patientId"}
error: "patientId null is invalid"
path: "/api/demographics/:patientId"

---------

{"error":"patientId null is invalid","path":"/api/demographics/:patientId"}

**Comment by kuvakina** [comment]
Bogdan fixed the issue by updating OneLondon:
	
1) Patient banner was fixed;
2) All functionality for patients was copied from NES to London;
3) initialize requests before patient summary redirecting
